[tools]
go = "latest"
node = "24.11.0"
"npm:@nestjs/cli" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:neovim" = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:vscode-langservers-extracted" = "latest"
python = "3.14"
rust = "latest"
usage = "latest"
uv = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.python]
compile = true
uv_venv_auto = true
