"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

command_timeout = 2000

[character]
success_symbol = '[➜](bold green)'

# Disable the package module, hiding it from the prompt completely
[gcloud]
disabled = true
