return {
    'nvim-treesitter/nvim-treesitter',
    config = function()
        require('nvim-treesitter.configs').setup({
            ensure_installed = {
                'bash',
                'c',
                'cmake',
                'cpp',
                'css',
                'diff',
                'gitignore',
                'glimmer',
                'go',
                'graphql',
                'html',
                'http',
                'javascript',
                'jsdoc',
                'json',
                'jsonc',
                'lua',
                'markdown',
                'markdown_inline',
                'python',
                'query',
                'regex',
                'rust',
                'scss',
                'sql',
                'terraform',
                'toml',
                'tsx',
                'typescript',
                'vim',
                'yaml',
            },
            highlight = { enable = true },
            query_linter = {
                enable = true,
                use_virtual_text = true,
                lint_events = { 'BufWrite', 'CursorHold' },
            },
            additional_vim_regex_highlighting = false,
        })
    end,
}
